# -*- coding: utf-8 -*-
"""basic_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wFSc8JBtCvKFWFCFWPtTuToH5xWmHWSi
"""

!pip install streamlit pdfplumber pyngrok

code = '''
import streamlit as st
import pdfplumber
import re
import pandas as pd

def extract_data(pdf_path):
    data = {
        "Card Type": None,
        "Card Last 4 Digits": None,
        "Billing Period": None,
        "Payment Due Date": None,
        "Total Amount Due": None
    }

    with pdfplumber.open(pdf_path) as pdf:
        text = ""
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text

    data["Card Type"] = re.search(r"(Platinum|Signature|Gold|Classic|Rewards)", text)
    data["Card Last 4 Digits"] = re.search(r"XXXX-XXXX-XXXX-(\\d{4})", text)
    data["Billing Period"] = re.search(r"Billing Period[:\\-]?\\s*(.*?to.*)", text)
    data["Payment Due Date"] = re.search(r"Payment Due Date[:\\-]?\\s*([A-Za-z0-9\\-]+)", text)
    data["Total Amount Due"] = re.search(r"Total Amount Due[:\\-]?\\s*([₹\\d,\\.]+)", text)

    for key, match in data.items():
        if match:
            data[key] = match.group(1) if match.groups() else match.group(0)
        else:
            data[key] = "Not Found"

    return data

st.set_page_config(page_title="🧾 Credit Card Parser", layout="centered")
st.title("📄 Credit Card Statement Parser")

uploaded_file = st.file_uploader("Upload your credit card PDF", type=["pdf"])

if uploaded_file:
    with st.spinner("🔍 Extracting info..."):
        extracted_data = extract_data(uploaded_file)
        df = pd.DataFrame([extracted_data])
        st.success("✅ Extracted Data:")
        st.dataframe(df)

        csv = df.to_csv(index=False).encode('utf-8')
        st.download_button(
            label="📥 Download CSV",
            data=csv,
            file_name="parsed_credit_card_data.csv",
            mime="text/csv"
        )
'''

with open('app.py', 'w') as f:
    f.write(code)

from pyngrok import ngrok
from pyngrok import ngrok

# Replace the string with your real token
ngrok.set_auth_token("34Jj8sKyyV7Vpf7ngQSxnnvHtcn_2RUxG1x3Rq4MjJkzJ1CiC")

# Open a tunnel on port 8501 (default Streamlit port)
public_url = ngrok.connect("http://localhost:8501")
print(f"Streamlit app will be available on: {public_url}")

# Run Streamlit app in background
!streamlit run app.py &>/dev/null &